<?php

/**
 * @file
 * Install, update and uninstall functions for the Opigno Course module.
 */

function opigno_course_update_9001() {
  module_load_include('install', 'opigno_lms', 'opigno_lms');

  _opigno_lms_apply_update('module', 'opigno_course', 'config/optional', ['entity_browser.browser.media_entity_browser_badge_images']);
  _opigno_lms_apply_update('module', 'opigno_module', 'config/optional', ['entity_browser.browser.media_entity_browser_file_pdf']);
}
